# MyCheatSheet - Package and release workflow
name: Package and release

# Release when pushing tags starting with 'v' (v1.0.0, v1.1.0, etc.)
on:
  push:
    tags:
      - 'v*'

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # Package and release job
  release:
    runs-on: ubuntu-latest

    # Environment variables for publishing to different platforms
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}           # CurseForge API key (optional)
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}   # Wago.io API token (optional) 
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}       # GitHub token (automatically provided)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for changelog generation

      # Package for retail WoW and create GitHub release
      - name: Package and release MyCheatSheet
        uses: BigWigsMods/packager@master
        with:
          args: -g retail -w 0

